server:
  port: 3377

spring:
  profiles:
    active: prod #配置的时候bootstrap.yml里的${spring.cloud.nacos.config}里的group和namespace也要对应上
    #active: dev # 表示开发环境
    #active: prod # 表示生产环境
    #active: test # 表示测试环境